### ISSUE TITLE
May 2014 Schema Changes

### ISSUE THREAD

**Issue by mineo** [alastair/python-musicbrainzngs#142]
Those include

- [x] Series ([MMD schema change](https://github.com/metabrainz/mmd-schema/commit/a0b8e2aa0f9e7f84ae74d8d9e6509e725fa2c169))
- [x] Instruments ([MMD schema change](https://github.com/metabrainz/mmd-schema/commit/12bdea6df3f382361ccd1009488213b47e77d71a))
- [x] Editor searches ([MMD schema change](https://github.com/metabrainz/mmd-schema/commit/645e196a06c1edc4135f01ed9939c93806a62240))
- [x] Work attributes ([MMD schema change](https://github.com/metabrainz/mmd-schema/commit/9a569e80395f55e947f67bfaf141ebd739cd0a09))

**Comment by alastair** [comment]
Relationship attributes are interesting. We now have two types - normal tickbox attributes, which are represented in an `attribute-list` as strings, e.g. the instrument that a "recording-artist plays" relation is:
https://beta.musicbrainz.org/relationship/59054b12-01ac-43ee-a618-285fd397e461
http://beta.musicbrainz.org/ws/2/recording/e8ab698b-6dac-4d28-a68d-0490edc2ac41?inc=artist-rels
```
<attribute-list>
<attribute>mridangam</attribute>
</attribute-list>
...
<attribute-list>
<attribute>lead vocals</attribute>
</attribute-list>
```
And attributes where the the value of the attribute can be entered:
https://beta.musicbrainz.org/relationship/b0d44366-cdf0-3acb-bee6-0f65a77a6ef0
https://beta.musicbrainz.org/ws/2/work/72c9aad2-3c95-4e3e-8a01-3974f8fef8eb?inc=series-rels
```
<attribute-list>
<attribute value="BuxWV 1">number</attribute>
</attribute-list>
```

From quick inspection, attributes with starts and ends are treated with the dates as part of the relation info, even though relation documentation says that it's an "attrbute" in the same text as additional instruments, etc: https://beta.musicbrainz.org/relationship/59054b12-01ac-43ee-a618-285fd397e461

Currently we store attributes as a list of strings (the first example): `{... "attributes":  ['lead vocals']}`
To add the second type of attributes we need to do something like a dict: `{... "attributes": [ {"attribute": "number", "value": "BuxWV1"}] }`, however, now we have two different forms of attribute lists.

* Do we expect people to inspect these and identify its type before using it?
* Can we know what type of attributes we will see based on the id of the relation? Is there a class of relations that we can identify easily without adding the entire relation tree into our source?
* How many other relations have these kinds of attributes?

**Comment by ianmcorvidae** [comment]
Some quick comments/responses:

a.) "Attributes with starts and ends" -- not sure what you mean; we don't support having dates on particular attributes of a relationship, only on the relationship itself. They're attributes of the particular relationship in the casual sense of the word but not in the precise "linked via link_attribute etc etc. in the database" way. They're unchanged from recent schema changes, in any case.
b.) "Do we expect people to inspect these and identify its type before using it?" -- probably, I guess -- we don't provide the link strings at all so it's hard to use them any other way than knowing what to properly do with any particular attribute type anyway. Certainly 'number' is not a useful piece of information by itself, vs. something like "lead vocals"
c.) "Can we know what type of attributes we will see based on the id of the relation?" -- not without information which we don't provide in the webservice, I think. We don't provide information about the types and their interrelations/allowed attributes/etc. in the webservice unless I'm unaware of a very obscure corner of the webservice, anyway.
d.) "How many other relations have these kinds of attributes?" -- The current two are the 'number' attribute, which is available on 'part of' relationships for RG, work, recording, event, and release series, and the 'time' attribute which is available on artist-event "main performer", "support act", "guest performer", "conductor", and "orchestra" relationships. We can, of course, add and change these at any time, it's not a schema change thing to add more text attributes or change what relationships support and use them.
e.) As far as the format, I'm not sure what's best -- if we do change it to a dict, which we probably need to, I'd do it for everything, and consider the value to be equal to the attribute name in the case of non-text attributes. This also provides a place to add link attribute type MBIDs if they make it into the webservice and a place to put 'ordering' values for applicable link types (presently: series parts, work parts, work-work medley, recording-recording compilation) as well. I suppose if we need to not change the API, this could be added as a new key, but that seems icky in its own way.

**Comment by alastair** [comment]
a) Regarding start/end, it's just that the relationship pages (https://beta.musicbrainz.org/relationship/59054b12-01ac-43ee-a618-285fd397e461) show 'start date' and 'end date' under the "attributes" heading, though I understand how they are stored directly on the relationship, rather than in the attribute list.
b) yeah, I agree with this. I would argue that 'cello' is not as useful as `<attribute value="cello">instrument</attribute>`, though that's a different story
c) Right. I didn't mean to imply that we get this from the WS, rather we store the relation uuids in pymb, and use this data to decide what types of attributes we get for a particular rel type. However...
d) Since you say that these can change at any time, the above may not be a good idea. I see for example https://beta.musicbrainz.org/relationship/936c7c95-3156-3889-a062-8a0cd57f8946 has both types of attribute (time, vocal/instrument). So this answers my second question - "can we know the style of attributes given the relation" - answer: no.

e) If we change all attributes to dicts, we break backwards compatibility. If we intersperse dicts in with the strings, we break backwards compatibility (people may just iterate through all attributes and expect them to be strings [I know I do in a few cases where I use performance rels])

**Comment by alastair** [comment]
finally, regarding `ordering`, it's in the xml tree as a child of relation, not a child of attribute-list or attribute. I'm not sure exaclty where you're proposing moving it to

**Comment by ianmcorvidae** [comment]
re b.) I'd much prefer `<attribute id="0db03a60-1142-4b25-ab1b-72027d0dc357">cello</attribute>` to either, but we don't currently provide link attribute type MBIDs (though they do match the instrument MBIDs for those attributes: https://musicbrainz.org/instrument/0db03a60-1142-4b25-ab1b-72027d0dc357). But that'd still need more information to determine that it's an instrument, for example, and we don't have endpoints for getting metadata about link and link attribute types. someday...
re e.) what I mean is we could have e.g. "`attributes": ["the", "same", "as", "before"]`, probably skipping entirely anything that's a text value (but not credited ones -- that basically being the difference, for credits the attribute name is more meaningful) *plus* add a new `"attributes-dicts": [{"attribute": ..., "value": ..., "credit": ..., ...}]` which has a new format and includes everything. But that's duplicating things for the sake of backwards compatibility, so it's a question which we care about more.

re: ordering you're right, the ordering is calculated from an attribute of the relationship but it's a property of the relationship itself rather than of the attribute, so it doesn't really apply here

**Comment by alastair** [comment]
I prefer to duplicate for the sake of backwards compatibility. It'd be great if we had objects instead of dicts and could raise deprecation warning on access to `"attributes"` :(
Anyway, as much as it's hacky, I like your suggestion as a failsafe way to be backwards-compatible. Let's come up with a better name for `attributes-dict` (your suggestion!)
```
8:12 PM <ianmcorvidae> if it has value="foo" then the text value of the node shouldn't make it into the backwards-compatibility list because it having a text value means the attribute name isn't very useful; but, if it has credited-as (or anything else, just not value) it should
8:13 PM <ianmcorvidae> unless you'd rather just include them even when the only information they provide is "this has a number. not telling you what it is without the full info though!" or so
8:13 PM <alastairp> ah, filter on value=“” as something to remove
8:13 PM <ianmcorvidae> yeah
8:13 PM <alastairp> yeah, leaving it in is not a terrible idea
8:13 PM <ianmcorvidae> since that indicates the attribute name (the text node value) isn't meaningful on its own
8:13 PM <ianmcorvidae> but if you're fine just including it then it's easy
8:13 PM <alastairp> to say “we’re including something to show you that it exists, but you need to use something else to get more useful data from it"
8:13 PM <ianmcorvidae> then it's truly no change from the current setup, other than adding the new key with the list of dicts
```

**Comment by alastair** [comment]
Instruments done

**Comment by alastair** [comment]
I see the editor MMD update, but I don't know any webservice endpoints which output editor information (there certainly isn't a `/ws/2/editor endpoint`). Unless someone points one out, we'll skip it.

**Comment by mwiencek** [comment]
The editor stuff is definitely unfinished, so I'd skip it. The current search server supports it internally\*, but MBS doesn't publicly expose it. Also, it might depend on SOLR work now if it doesn't exist in the new search code.

\* http://search.musicbrainz.org/ws/2/editor?type=editor&query=foo
