### ISSUE TITLE
Use HTTPS for web service queries

### ISSUE THREAD

**Issue by Freso** [alastair/python-musicbrainzngs#197]
MusicBrainz is now planning to go all HTTPS-only in the future. To begin with, only the non-/ws/ sections of the page with be HTTPS-only, but it is planned that eventually everything will only be accessible through HTTPS - so python-musicbrainzngs should probably make the switch sooner rather than later. :)

Relevant upstream ticket: https://tickets.musicbrainz.org/browse/MBH-363

**Comment by mineo** [comment]
Does MB use SNI? That is not supported on all Python versions we support.

**Comment by gentlecat** [comment]
Yes, we've had issues with that before. In CritiqueBrainz we had to add some hacks to access MBS via HTTPS.

**Comment by alastair** [comment]
I don't mind dropping support for python 2.6 if we need to. Are there any other possible workarounds?

**Comment by gentlecat** [comment]
https://github.com/metabrainz/critiquebrainz/blob/master/critiquebrainz/__init__.py#L3-L9

**Comment by alastair** [comment]
Right, https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484 shows something similar. We could leave it as "supported with this caveat"

**Comment by gentlecat** [comment]
Also keep in mind that 2.7 started supporting SNI and a bunch of other things only from 2.7.9.

**Comment by sampsyo** [comment]
Looks like Requests (i.e., #123) also [supports SNI](http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors).

**Comment by alastair** [comment]
Yep. I'm happy to start considering requests again, but this won't help anyone using older versions of the library

**Comment by alastair** [comment]
We talked about this in IRC. Our plan is to:
  * default to https://musicbrainz.org
  * update `set_hostname` with a new parameter `use_https=False`

The new parameter should default to false so that it's backwards compatible with existing code which already calls `set_hostname` expecting it to connect to an http endpoint

**Comment by hugovk** [comment]
It's about time to drop Python 2.6 anyway, it's been EOL since 2013 and many packages have already dropped support meaning it's getting harder to support and test.

Luckily, usage is low.

Here's the pip installs for musicbrainzngs from PyPI for the last month:
```
$ pypinfo --percent --pip musicbrainzngs pyversion
python_version percent download_count
-------------- ------- --------------
2.7              48.0%            617
3.6              29.6%            380
3.5              18.1%            232
3.4               3.4%             44
2.6               0.4%              5
3.3               0.3%              4
3.7               0.2%              3
```

Python 3.2 and 3.3 are also now EOL, and have even lower numbers, so you could consider dropping those too.

Thoughts?

**Comment by Freso** [comment]
Considering that Python 2 will be dead in [less than a year](https://pythonclock.org/), maybe we can just bump the minimum version for the next release (0.7 or 1.0) to Python 2.7.6+ and any future releases by Python 3 only?
