### ISSUE TITLE
Accesses network during build

### ISSUE THREAD

**Issue by alastair** [alastair/python-musicbrainzngs#201]
Bug report from debian - it looks like it's something to do with docs, but I don't know why we make this query.

Dear Maintainer,

Whilst musicbrainzngs builds successfully on unstable/amd64, according to
Debian Policy 4.9 packages may not attempt network access during
a build.

  00:00:00.000000 IP 8f5bcc31f32b.58302 > dnscache.uct.ac.za.domain: 53135+ A? python-discid.readthedocs.org. (47)
  00:00:00.000040 IP 8f5bcc31f32b.58302 > dnscache.uct.ac.za.domain: 47666+ AAAA? python-discid.readthedocs.org. (47)
  00:00:00.237007 IP dnscache.uct.ac.za.domain > 8f5bcc31f32b.58302: 47666 0/1/0 (117)
  00:00:00.237028 IP dnscache.uct.ac.za.domain > 8f5bcc31f32b.58302: 53135 1/2/2 A 162.209.114.75 (150)
  00:00:00.237423 IP 8f5bcc31f32b.43324 > readthedocs.org.http: Flags [S], seq 4036759599, win 29200, options [mss 1460,sackOK,TS val 105869558 ecr 0,nop,wscale 7], length 0
  00:00:00.244310 IP readthedocs.org.http > 8f5bcc31f32b.43324: Flags [S.], seq 578772648, ack 4036759600, win 5792, options [mss 1460,sackOK,TS val 717584677 ecr 105869558,nop,wscale 1], length 0

**Comment by alastair** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830186

**Comment by mineo** [comment]
I'm not sure if we're able to fix this or if this is something that needs to be handled in the debian package. The inventory file for python-discid is probably used for at least https://github.com/alastair/python-musicbrainzngs/blob/master/musicbrainzngs/musicbrainz.py#L998.

**Comment by JonnyJD** [comment]
I don't think this is a problem on our end.

The internet access is for the created docs to be able to link to other docs on the net for classes and functions. In this case python-discid.
See: http://python-musicbrainzngs.readthedocs.io/en/v0.6/api/#musicbrainzngs.get_releases_by_discid
where  `discid.Disc.toc_string` is linked to the python-discid docs.

This could potentially be solved differently in sphinx. For javadoc you can download a list of classes for an online documentation and use that to build links without internet access when building docs.
However, I don't see this change coming to sphinx soon.

The fix for debian is to either not build the docs (since they are online anyways) or patch the doc building to not use interlinks.

**Comment by JonnyJD** [comment]
This was fixed in Debian.
